language: python

# for container-y googdness:
sudo: false

python:
  - "2.7"

# command to install dependencies
install: "pip install -Ue .[test,build]"

# command to run tests, e.g. python setup.py test
script: nosetests --with-cov --cov=archivist

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: x
  on:
    tags: true
    repo: Simplistix/archivist
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
