language: python

# for container-y googdness:
sudo: false

python:
  - "2.7"

install:
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test User"
  - git config --global push.default simple
  - "pip install -Ue .[test,build]"

# command to run tests, e.g. python setup.py test
script: coverage run -m nose

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: x
  on:
    tags: true
    repo: Simplistix/archivist
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
